### ISSUE TITLE
道具中手铐功能有bug

### ISSUE THREAD

**Issue by echo-xianyu** [Agnes4m/nonebot_plugin_BR#2]
使用时可能会出现手铐效果不生效，或者使用后自己的回合被跳过
![Image_1730775813950](https://github.com/user-attachments/assets/d931189f-dfba-410b-834b-6598b4264920)

**Comment by Agnes4m** [comment]
是有这个bug，最近比较忙，过几天才能试试）

**Comment by Agnes4m** [comment]
忘记提交0.0.3版本导致手铐错误的版本在pypi上。。
现已更新0.0.4版本
