### ISSUE TITLE
几个Bug以及建议

### ISSUE THREAD

**Issue by reine-ishyanami** [Agnes4m/nonebot_plugin_BR#3]
# Bug
1. 使用道具的时候没有进行鉴权，导致在我方回合时，对方发出使用道具指令，会直接使用我方道具
2. 手铐逻辑问题（复现：在对对方使用手铐后，开枪打自己是空弹的时候，手铐直接解开并且移交下回合的开枪权力给对方）

# 建议
1. 使用饮料退弹后提示退出的子弹类型
2. 游戏中途可以主动查看本场游戏状态

**Comment by Agnes4m** [comment]
道具使用的时候，我使用round_self来的bool来判断是否是玩家一行动，双方道具在两个键下应该是相互独立无交错的。
其次手铐逻辑确实有问题，我目前还没找到问题在哪里（）

**Comment by Agnes4m** [comment]
![image](https://github.com/user-attachments/assets/3dcfdb66-d38c-4c7a-8c59-b868e16d8ebf)
- 测试道具并不会使用对面的
- 手铐的修了下目前测试没问题
- 新增`br当前状态`来查询
- 饮料效果本来就不应该提醒退弹的类型，这属于违背游戏规则，但是交给对面开枪后则知道退弹类型，属于一个bug

已提交新版本，测试下看看

**Comment by reine-ishyanami** [comment]
道具使用疑似仍有bug，安装方式是直接使用 git clone 的，应该和仓库代码一致
![1e1ff70ec0559f91830df85fe8286087_720](https://github.com/user-attachments/assets/5fdde390-6fa3-4e59-8b6d-c7655132d44e)

# 建议
1. 开局后可以发送游戏状态，在使用过程中发现开局时弹匣状态未知，道具未知，血量未知
2. 在查看当前状态时可以显示当前持有开枪权的玩家

**Comment by Agnes4m** [comment]
这周考试完就搞，

**Comment by Agnes4m** [comment]
已更新
