### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by D-6CF-X** [Agnes4m/nonebot_plugin_BR#5]
![FB063C5CCE7A46D55934B5AAF566E3F7](https://github.com/user-attachments/assets/ec7dc34e-0183-4e32-83cb-608fca432083)
逻辑有误，太乱了后面开枪理不清回合了。截图前面用户千里一回合使用2个手铐，生效一个，吞了一个；我不能连续连续2回合都用刀

**Comment by D-6CF-X** [comment]
![image](https://github.com/user-attachments/assets/0ded4e83-549b-4678-9d48-82d75c526b74)
补充

**Comment by Agnes4m** [comment]
这周考试完就更新

**Comment by Agnes4m** [comment]
已更新
